### ISSUE TITLE
Saving of templates

### ISSUE THREAD

**Issue by teigentler** [BCCHR-IT/custom-template-engine#1]
I installed Custom Report Builder with the current RedCap version (9.1) and adjusted the paths accordingly.
Creating a template works in such a way that the plugin indicates that the template has been saved. However, no template appears in the template list (and also no one is saved in the according directory on the server)
Any hints?

**Comment by BCCHR-IT** [comment]
Hello, May you send any screenshots of your configuration? It's difficult for me to assist otherwise.

**Comment by teigentler** [comment]
Dear Ashley,

thank you for your prompt reply.

Please see the config. screenshot:

Kind regards

Thomas

Von: BCCHR - REDCap <notifications@github.com>
Gesendet: Montag, 17. Juni 2019 18:11
An: BCCHR-IT/custom-report-builder <custom-report-builder@noreply.github.com>
Cc: teigentler <thomas@eigentler.de>; Author <author@noreply.github.com>
Betreff: Re: [BCCHR-IT/custom-report-builder] Saving of templates (#1)


Hello,

May you send any screenshots of your configuration? It's difficult for me to assist otherwise.

Sincerely,
Ashley

**Comment by BCCHR-IT** [comment]
Hello Thomas,

May you re-upload the screenshot? I cannot see it.

Sincerely,
Ashley

**Comment by teigentler** [comment]
Sorry. Please find it attached.
![ScreenShot](https://user-images.githubusercontent.com/18628021/59624422-0125e400-9137-11e9-9541-ad367453e29c.jpg)

**Comment by BCCHR-IT** [comment]
Hello Thomas, 

Are these folders writable by REDCap? Could you also check the REDCap logs, and send a screenshot of any recent messages related to the report builder? In regards to template creation, the action should be 'Template created'

Sincerely,
Ashley

**Comment by teigentler** [comment]
Dear Ashley,

I discovered the problem. The folders have to be owned by the same user as the RedCap installation. 

All the best
Thomas

**Comment by BCCHR-IT** [comment]
Hello Thomas,

Glad to hear.

Sincerely,
Ashley
