### ISSUE TITLE
Records not limiting on DAGs

### ISSUE THREAD

**Issue by raigs-bham** [BCCHR-IT/custom-template-engine#11]
Records are not being restricted to the logged in users DAG. 

Currently a user can select all records including records in other DAGs. If a user has been assigned to a DAG then that user should only see records within their DAG. A user that has not been assigned a DAG can see all records.

Can you fix this issue?

Thanks

**Comment by BCCHR-IT** [comment]
Hello,

Sorry for the late response. Yes, this is a bug that can be fixed for our next release.

**Comment by BCCHR-IT** [comment]
An update on this bug, this has been fixed and will be released with the v3.0 update that we're currently testing.
