### ISSUE TITLE
mass generation of pdfs

### ISSUE THREAD

**Issue by mschulze0** [BCCHR-IT/custom-template-engine#12]
Hi,

is there a way I can (with some function call) generate many pdfs without user input? I have a list of records and a list of templates and need pdfs for each record-template pair. It would take too long to go through all of it by hand.

**Comment by BCCHR-IT** [comment]
Hello,

Sorry for the late response. There's no way to do this currently, and it's not something we're looking to implement. The closest thing we're currently working on is allowing users to batch-fill multiple reports by hand, however, there's no determined release data for that feature yet, and I understand it doesn't fill you needs.

**Comment by mschulze0** [comment]
@BCCHR-IT ok that's fine. I will implement it myself.

**Comment by mschulze0** [comment]
@BCCHR-IT we now added a new button to the interface where you can enter a record ID from a separate, helper project. in that project there is a repeating form which contains record IDs from the primary project (pulled in via the cross-project piping module) and for each record ID it has variables that specify which templates should get created for that record ID. So when you enter a record ID from the helper project and click the button it will then automatically generate all those pdfs and download them as a zip file.

We're now in the process of generalizing it so it can be employed by other users.

**Comment by BCCHR-IT** [comment]
That's great! I'm glad you've found a solution.
