### ISSUE TITLE
Can save the custom temple but can't find it to use or edit

### ISSUE THREAD

**Issue by hengb** [BCCHR-IT/custom-template-engine#13]
do we need to configure something on custom report build?

**Comment by BCCHR-IT** [comment]
Hello,

Apologies for the late response. When you initially enable the module, you should've configured a place to store your templates. Where are your reports saved? When you check that location in the server are you able to find them?

**Comment by hengb** [comment]
Hello,

Thank you. Yes it's works.
Currently, I'm working on one project but it separate in 2 databases, one for clinical data and an other for laboratory results.

It is possible to link the field between 2 databases to show in one report?

Best,
Bun Heng


Best regards,
Bun Heng
Database Developer/HelpDesk
U.S. Naval Medical Research Unit.2 (NAMRU-2)
Email: heng.bun.ctr@namru2.org.kh / heng.bun@outlook.com
Office: (855) 23 -883-562 ext. 120
HP: (855)69-845-678

________________________________

**Comment by BCCHR-IT** [comment]
Hello,

I'm glad you've got the module working. 

Unfortunately, linking fields between 2 databases isn't possible.

**Comment by hengb** [comment]
Hello,

Thanks you for your help.
I hope it will be worked for an other new version.


Best regards,
Bun Heng
Database Developer/HelpDesk
U.S. Naval Medical Research Unit.2 (NAMRU-2)
Email: heng.bun.ctr@namru2.org.kh / heng.bun@outlook.com
Office: (855) 23 -883-562 ext. 120
HP: (855)69-845-678

________________________________
