### ISSUE TITLE
export of chinese characters to PDF does not function

### ISSUE THREAD

**Issue by devincowan** [BCCHR-IT/custom-template-engine#14]
We have added Chinese characters to one of our templates and note that they don't appear in the filled PDFs (they are replaced with blanks).

Love this tool, thanks!

**Comment by devincowan** [comment]
I made an effort at some simple changes in this pull request: #15 
I had to duplicate the creation of Dompdf() because `$filled_template_pdf_content = $dompdf->output();` causes the later `$dompdf->stream($filename);` to not export later in CustomTemplateEngine

**Comment by BCCHR-IT** [comment]
Hello,

I'm glad you've enjoyed the module! But we haven't added any language support to the module. I'll take a look at your changes and see if we can integrate them, as we're currently testing a major update. Please let me know how the changes work out on your end.
