### ISSUE TITLE
Image not found or type unknown for external image link

### ISSUE THREAD

**Issue by jlmnrc** [BCCHR-IT/custom-template-engine#16]
When embedded an image, the generated PDF is showing:

Image not found or type unknown

[Barcode - 2 (1).pdf](https://github.com/BCCHR-IT/custom-template-engine/files/5126882/Barcode.-.2.1.pdf)

**Comment by jlmnrc** [comment]
After researching about dompdf, if I insert this statement at CustomTemplateEngine.php line 1257, it will solve the issue:
`$dompdf->set_option("isRemoteEnabled", true);`

**Comment by BCCHR-IT** [comment]
Integrated and to be released in the next release (v3.1).
