### ISSUE TITLE
Slow loading page

### ISSUE THREAD

**Issue by MathiasAntunes** [BCCHR-IT/custom-template-engine#19]
Hi,

I've been noticing really slow loading time of the external module page (>60seconds).
I've noticied it happens on big project (3000+ records) and with custom record label enabled.

 ̶L̶o̶o̶k̶i̶n̶g̶ ̶i̶n̶ ̶t̶h̶e̶ ̶S̶Q̶L̶ ̶R̶E̶D̶C̶a̶p̶ ̶p̶a̶n̶e̶l̶,̶ ̶i̶'̶v̶e̶ ̶n̶o̶t̶i̶c̶e̶d̶ ̶t̶h̶a̶t̶ ̶t̶h̶e̶ ̶S̶Q̶L̶ ̶r̶e̶q̶u̶e̶s̶t̶ ̶t̶a̶k̶e̶s̶ ̶a̶ ̶r̶e̶a̶l̶l̶y̶ ̶l̶o̶n̶g̶ ̶t̶i̶m̶e̶ ̶:̶ ̶
̶"̶s̶e̶l̶e̶c̶t̶ ̶r̶e̶c̶o̶r̶d̶,̶ ̶f̶i̶e̶l̶d̶_̶n̶a̶m̶e̶,̶ ̶v̶a̶l̶u̶e̶ ̶f̶r̶o̶m̶ ̶r̶e̶d̶c̶a̶p̶_̶d̶a̶t̶a̶ ̶w̶h̶e̶r̶e̶ ̶p̶r̶o̶j̶e̶c̶t̶_̶i̶d̶ ̶=̶ ̶1̶3̶ ̶a̶n̶d̶ ̶f̶i̶e̶l̶d̶_̶n̶a̶m̶e̶ ̶i̶n̶ ̶(̶'̶r̶e̶c̶o̶r̶d̶_̶i̶d̶'̶,̶ ̶'̶_̶_̶G̶R̶O̶U̶P̶I̶D̶_̶_̶'̶)̶ ̶g̶r̶o̶u̶p̶ ̶b̶y̶ ̶r̶e̶c̶o̶r̶d̶,̶ ̶f̶i̶e̶l̶d̶_̶n̶a̶m̶e̶ ̶o̶r̶d̶e̶r̶ ̶b̶y̶ ̶r̶e̶c̶o̶r̶d̶,̶ ̶f̶i̶e̶l̶d̶_̶n̶a̶m̶e̶ ̶d̶e̶s̶c̶"̶

Thanks !

**Comment by BCCHR-IT** [comment]
Hi,

While there's some slowness in our projects with over 3000 records, they don't more than 60 seconds. Are you sure that SQL query is related to the module? We don't use a query like that in our code.

**Comment by MathiasAntunes** [comment]
Oh, actually this SQL is not related, my bad ! 
It is mostly related to the script retrieving custom label I think.

I did some testing and on our 45k record project we have : 
  With custom record label : 2min loading
  Without custom record label : 13sec loading

On 6k record project : 
  With complex custom record label : 60sec loading
  Without custom record label : 1sec loading


Thank you for the amazing module btw !

**Comment by BCCHR-IT** [comment]
I'm glad you're enjoying it. We'll take a look at this when we can, but I cannot promise a swift update. My suggestion for now is to comment out the custom record label in the code.

**Comment by BCCHR-IT** [comment]
Retrieval of custom record labels has been changed for the next release (v3.1). Custom labels are all now retrieved before the loop the builds the record dropdown, rather than within, which should speed up the loading time.
