### ISSUE TITLE
Template folder path has to end with a trailing directory separator

### ISSUE THREAD

**Issue by grezniczek** [BCCHR-IT/custom-template-engine#2]
If the folder paths are not supplied with a trailing directory separator (/ on Linux, \ on Windows), at least when creating a template, it will be stored in the parent folder (and has the foldername prependend to the filename). The module then naturally does not "see" this template any more. When the templates is moved to the correct folder, it is then seen by the module.
This occurs at least on Windows. Seen with v2.9 of the module.

**Comment by BCCHR-IT** [comment]
Hello Gunther,

You're correct. Thank you for bringing this issue up, we'll put it on our list of fixes.   

Sincerely,
Ashley

**Comment by BCCHR-IT** [comment]
As of the re-branding from Custom Report Builder to Custom Template Engine (v2.9.1), this issue has been fixed.
