### ISSUE TITLE
no access for some users

### ISSUE THREAD

**Issue by mschulze0** [BCCHR-IT/custom-template-engine#21]
Hi,

are there any tricks/certain permission settings to ensure users have access to the CTE page? I can't figure out why some users can access the CTE page but other users get a message saying they don't have permission to access the page.

**Comment by BCCHR-IT** [comment]
Hello,

Please check that your users have Data Export rights higher than 'No Access'. This should allow them to access the module, and fill/download reports. For creating/editing/deleting reports please check the README in the repo for the additional rights to grant.
