### ISSUE TITLE
Fill template on record save, save PDF to field on record

### ISSUE THREAD

**Issue by lsgs** [BCCHR-IT/custom-template-engine#22]
Thanks for the module. We've been finding it very helpful! We have a use case where we would love the facility for having a template automatically filled for a record when a form is saved, then have the PDF saved to a file upload field.

I will be able to do some development and submit a PR, but thought I'd ask if you have any thoughts/ideas/preferences around the best way to go about implementing something along those lines? 

- How to trigger the filling of a template and generation of the PDF from within the redcap_save_record hook?
- How to configure the (event/)field to save to for a particular template?

Thanks!

**Comment by remifrazierucsf** [comment]
@BCCHR-IT we see this issue as closed, but without a response - can you give us some details on this issue/feature request?  We have a strong need for this as well.

**Comment by BCCHR-IT** [comment]
Hello, this issue was closed because we'd contacted the requester directly, and worked with them on the development of this. A pull request has been submitted and will be reviewed, but as our team is quite busy with other work at the moment, it will be a while before this functionality is available.

**Comment by remifrazierucsf** [comment]
Amazing - thank you for the fast reply - @BCCHR-IT @lsgs if I can help with a PR review on this let me know.

**Comment by remifrazierucsf** [comment]
@BCCHR-IT is there any chance that this feature request will be (or has been) merged in for the next release? We can provide some engineering support for this if that would help.
