### ISSUE TITLE
Extremely slow index page load

### ISSUE THREAD

**Issue by tertek** [BCCHR-IT/custom-template-engine#24]
The module is loading **all records** into the drop-down field each time the module page is opened. 

`
    $records = json_decode(REDCap::getData("json", null, array($id_field), null, $rights[$this->userid]["group_id"]), true);
`

We have 50k records which takes about 5 minutes to load. Of course we cannot use the module in this way. The approach of loading a full record list is not practical and should be avoided. I have had a similar issue like this with the Mass Delete Module. I think a design change would be also good in this case. So instead of selecting from a record list, the user should input a record ID which would be validated before passed to the template validation.

**Comment by tertek** [comment]
https://github.com/BCCHR-IT/custom-template-engine/pull/25

**Comment by BCCHR-IT** [comment]
Hello, thank you for this suggestion and the work you've put in. We prefer a dropdown with our projects, but understand it's not ideal for everyone. We will look over your changes when we can.

**Comment by tertek** [comment]
Hey there,
I added the manual selection as optional. It is not removing your preferred choice.
