### ISSUE TITLE
Module is disabled automatically after REDCap cron jobs

### ISSUE THREAD

**Issue by jgardner-qha** [BCCHR-IT/custom-template-engine#27]
After installing the module, it seems to work great until a standard REDCap cron job runs. REDCap sends an e-mail automatically after this happens:

`[This message was automatically generated by REDCap]

The 'custom_template_engine' module was automatically disabled because of the following error:

Error: Undefined constant "BCCHR\CustomTemplateEngine\USERID" in /opt/projects/redcap/modules/custom_template_engine_v3.1.1/CustomTemplateEngine.php:43
Stack trace:
#0 /opt/projects/redcap/redcap_v10.9.4/ExternalModules/classes/ExternalModules.php(3176): BCCHR\CustomTemplateEngine\CustomTemplateEngine->__construct()
#1 /opt/projects/redcap/redcap_v10.9.4/ExternalModules/classes/ExternalModules.php(1745): ExternalModules\ExternalModules::getFrameworkInstance()
#2 /opt/projects/redcap/redcap_v10.9.4/Classes/Jobs.php(159): ExternalModules\ExternalModules::validateAllModuleCronJobs()
#3 /opt/projects/redcap/redcap_v10.9.4/Classes/Cron.php(311): Jobs->ExternalModuleValidation()
#4 /opt/projects/redcap/redcap_v10.9.4/cron.php(20): Cron->execute()
#5 /opt/projects/redcap/cron.php(9): include('...')
#6 {main}`

This server is running REDCap 10.9.4 using PHP-FPM 8.0.3 on Ubuntu 18.04.5 LTS. We also tried switching back to PHP 7.4 with the same results. This is the only module that appears to have any problem.

**Comment by jgardner-qha** [comment]
I found a way to fix this problem in the code. Keep in mind, I am _not_ a programmer. I can try to do a pull request for this but I don't use GitHub often and I don't want to mess something up.

This is what I did:

[Line 43](https://github.com/BCCHR-IT/custom-template-engine/blob/6228b1e5fadd7f8f61fdf1c924efc6bc94bc0e04/CustomTemplateEngine.php#L43)

I changed this line 43, CustomTemplateEngine.php, referenced above:
`$this->userid = strtolower(USERID);`
to this:
`$this->userid = (defined('USERID') ? strtolower(USERID) : null);`

Rationale:
When the cron job runs, it executes the construct, but the USERID constant is not defined. In this case, I added a simple sanity check to see if the USERID constant is defined before assigning its value to a variable.

**Comment by BCCHR-IT** [comment]
Hello, we'll take a look at this. I'm glad you found a solution, but as we're quite busy at the institute at the moment, I cannot guarantee a fast response from our end.

**Comment by jgardner-qha** [comment]
No worries! Huge thanks for all the work you've done on this.

My solution is working fine, and I'm very, very happy with the module. REDCap's PDF generation just isn't robust enough for our needs.


Jonathan Gardner
Network Administrator

Quality Health Associates of North Dakota
41 36th Ave NW | Minot, ND 58703
Phone (701) 989-6237 | Fax (701) 857-9755

***@***.******@***.***>

www.qualityhealthnd.org<http://www.qualityhealthnd.org/>



HIE / Direct Secure Messaging Address
***@***.***




________________________________

**Comment by BCCHR-IT** [comment]
Hi @jgardner-qha ,
We are about to release CTE v3.2.0 and this change has been implemented. Thank you for the report! I'll close this issue.
