### ISSUE TITLE
Image into custom template external module

### ISSUE THREAD

**Issue by GracePTKI** [BCCHR-IT/custom-template-engine#28]
Have tried uploading an image onto the server and it appears blank.  The image is unable to be found when I put into a report template.  Have attached picture of the issue where there is space uploaded but not showing the actual image. 

![Picture1](https://user-images.githubusercontent.com/85091931/120138583-50bd2780-c209-11eb-8f00-0902593b8557.png)

**Comment by BCCHR-IT** [comment]
Could you verify that your image has been uploaded to the folder you've set, and go into the Source view and verify that the value of 'src' is correctly pointing to where it's located? Screenshots of the source view would also help identify the problem.

**Comment by GracePTKI** [comment]
Hi,

I just chatted to our redcap team and it seems the source folder that the image is being uploaded to is incorrect, we didn't set the folder pathway, is there a way to set it? 
![github](https://user-images.githubusercontent.com/85091931/121835846-ceeaf500-cd04-11eb-80a9-f86bbcfc2016.png)

**Comment by BCCHR-IT** [comment]
You can set the pathway under Control Center > External Modules.

**Comment by GracePTKI** [comment]
okay thanks so much! I didn't have access to the control centre so I got our redcap team to change that file pathway. Last thing, now when uploading the image it looks like this on the pdf:
![imgnotfound](https://user-images.githubusercontent.com/85091931/122006141-134fc100-cde9-11eb-88ec-9f46d940e467.png)

I've seen that this has been a problem for others and that converting to base64 is potentially a solution but was wondering if there was another way?

**Comment by BCCHR-IT** [comment]
There was a problem with this in older versions that should be fixed in the latest version. It was due to how the image was accessed in the src attribute. Can you confirm that the src attribute of your image is a complete url that points to your image in the new folder location you've set? For example it should look something like https://redcap.ca/image_folder_location/image.jpg.

**Comment by GracePTKI** [comment]
oh okay i see, yeah the url of the src location is now this so i think it is correct:
![src_image](https://user-images.githubusercontent.com/85091931/122492136-d0276500-d017-11eb-865c-d65dcdf089b4.png)

**Comment by BCCHR-IT** [comment]
Thank you! The url looks alright. Could you verify that allow_url_fopen is set to true in php.ini? It's an optional configuration for the dependency to build the url in the module (https://github.com/dompdf/dompdf/wiki/Requirements).

This goes against what I was saying earlier, but you could also convert the full url to an absolute path just to see if that makes any difference.

**Comment by GracePTKI** [comment]
Okay, we tried those fixes and they haven't seemed to work we just wanted to confirm the module will work with the REDCap Version: 11.0.3 with Php Version: 7.4.11?

**Comment by BCCHR-IT** [comment]
That may be the issue! Our servers are currently on 7.2.34 and REDCap LTS v10.6.25, so I cannot confirm whether they'll work with your newer versions.

**Comment by BCCHR-IT** [comment]
Hello @GracePTKI this is a very old thread, and the CTE has been update since then. Are you still having this issue, or may I close this?

**Comment by BCCHR-IT** [comment]
Closing this chain, as CTE is now on v4.0.0, and if a problem persists it may be a different cause. If this bug persists after you have upgraded to the most recent version of CTE, please start a new issue.
