### ISSUE TITLE
citation

### ISSUE THREAD

**Issue by mschulze0** [BCCHR-IT/custom-template-engine#29]
Hi,

we are planning to mention your module in an upcoming publication. Is there any publication we can cite regarding this module or any citation format you would like us to use?

**Comment by BCCHR-IT** [comment]
That's amazing! What kind of publication is this? We don't have any publications to give you, however, and the citation format shouldn't matter.

**Comment by mschulze0** [comment]
@BCCHR-IT it's a publication about automation in our lab for which we're using this module :) (and we did extend the module a little bit)

But it would be nice if you could give me a list of people to attribute the module to. Just to make sure we're crediting the correct people.

**Comment by BCCHR-IT** [comment]
The config.json in the repository should point you to the primary developers of the module.
