### ISSUE TITLE
pdf options

### ISSUE THREAD

**Issue by mschulze0** [BCCHR-IT/custom-template-engine#3]
Hi,

it would be great to be able to select pdf paper size and a landscape option! Thanks a lot, this is a great module!

**Comment by BCCHR-IT** [comment]
Hello,

Apologies for the late response. I'm glad you're enjoying the module! We can discuss this possibility, but unless it's heavily requested among our users at BCCHR, I cannot guarantee it will be added.

**Comment by mschulze0** [comment]
@BCCHR-IT Hi,
paper size option would be nice to have, but landscape would be super useful as I have problems fitting some tables in portrait orientation
