### ISSUE TITLE
Issues with Downloading PDF/Save Report Options

### ISSUE THREAD

**Issue by tjane1596** [BCCHR-IT/custom-template-engine#31]
Hi, 

I'm trialling this module for the first time on my REDCap project (REDCap version 10.6.15). I have created a simple template using just two fields to start off with. The template has saved successfully and the document preview appears correct. 

However, these are the error messages I am receiving when saving the report to a field and downloading the PDF. 

![error1](https://user-images.githubusercontent.com/52337751/125387012-dbc83a80-e3cf-11eb-94dc-6a2f23ef8f19.jpg)
![error2](https://user-images.githubusercontent.com/52337751/125387065-e71b6600-e3cf-11eb-8981-53ec039bd8a7.png)

If I open the downloaded PDF in Adobe, the error message that appears is :
![Screenshot 2021-07-13 114711](https://user-images.githubusercontent.com/52337751/125387184-1631d780-e3d0-11eb-9cbe-f75ad2381e47.png)

Thanks for your assistance!
Tracie

**Comment by BCCHR-IT** [comment]
Hello, there may be some structural problems in your template's HTML. If you're okay with sending it over, I can take a look.

**Comment by remifrazierucsf** [comment]
Can you also check the filesize on the PDF? This might also be a write permissions problem.
________________________________

**Comment by BCCHR-IT** [comment]
Sure, I can also check the file size. If you think this might be a write permissions issue, then please check that redcap has been granted the appropriate access rights.

**Comment by tjane1596** [comment]
Hi, 

Thanks for getting back to me. This is the html code: 

```
<p>{$redcap[&#39;first_name&#39;]}</p>

<p>{$redcap[&#39;surname&#39;]}</p>
```

The size of the PDF when downloaded is 20KB. 

"If you think this might be a write permissions issue, then please check that redcap has been granted the appropriate access rights." -  I do currently have full access to the project but I might have to contact my institutions' REDCap admin if there are limitations to my account?

Tracie

**Comment by BCCHR-IT** [comment]
Hello,

There shouldn't be any issue with that HTML code, or your filesize. I was under the impression you had access to the REDCap backend! My mistake, your REDCap account permissions shouldn't have any effect on the issues you're seeing. 

This is a question for your REDCap admin, but what PHP version are you running? I received another email with similar issues and it turns out they were running PHP 7.4, when we run PHP 7.2, which seemed to be the problem. I plan on updating this in our next release.
