### ISSUE TITLE
Image not Uploading to Server 

### ISSUE THREAD

**Issue by tjane1596** [BCCHR-IT/custom-template-engine#32]
Hi team! 

I have come across an issue with uploading images into the module on REDCap where they come up blank.

![image](https://user-images.githubusercontent.com/52337751/131098459-ba1173ee-152e-428e-adbd-19529260a516.png)

I have attempted two work arounds to this: 

1. Adding a URL to the image in the source code which appears when the template is filled. But, when I download the PDF it appears as a large grey X on the document (screenshot below).
                                        Sample: `<p><img alt="" src="https://image.jpg" style="width:550px" /></p>`
2.Created a descriptive field with the image embedded but this field type does not work in this module – just comes up blank 

![image](https://user-images.githubusercontent.com/52337751/131098946-f2da44fd-7d31-407c-a8f6-83e1d29c75b6.png)

I have spoken to the server admins but they are unable to provide support for this issue. I'm hoping you may have some advice. 

Thanks!

Cheers,
Tracie

**Comment by BCCHR-IT** [comment]
Could you tell me what PHP version you're using? We've had similar issues with users who're on PHP 7.4.x, which has been added as a limitation to the module for now, as our servers use PHP 7.2.x.

**Comment by tjane1596** [comment]
Hi, 

That might be the issue! Info from my server admin below: 

Server info: REDCap 10.6.28 · PHP 7.4.20 (Windows OS) · MariaDB 10.3.12

Tracie

**Comment by BCCHR-IT** [comment]
Thank you for the information. Another user was able to confirm that they're experience the same error on PHP 7.2.x as well, so we're going to take a look at this. Unfortunately, for now, you'll have to avoid using images in your template.

**Comment by BCCHR-IT** [comment]
We are going to close this issue, as there have been several updates to CTE in the last two years, and PHP 7.2 is no longer supported by REDCap. Please use the most recent available version of the CTE for your installation
