### ISSUE TITLE
special characters not showing in pdf

### ISSUE THREAD

**Issue by mschulze0** [BCCHR-IT/custom-template-engine#4]
Hi,

I'm trying to use some special HTML characters like &darr; and other arrows. They are showing up fine on the website but when downloading the pdf none of them are showing up. I also tried all available fonts, but none of them work.

**Comment by BCCHR-IT** [comment]
Hello,

The fonts currently in use don't support special HTML characters, when downloading a PDF. A new font, DejaVu Sans, sans-serif, will be added with our v3.0 release that will.

Unfortunately, I cannot replicate your issue with the fonts not showing on our servers. In the Source View of your report, you should see all elements surrounded with a <span> element that contains the style attribute with the font-family set. Can you confirm that is the case when you try to use a font?

**Comment by mschulze0** [comment]
@BCCHR-IT great, looking forward to the new release then!
No, regarding the fonts I meant something else: I meant regardless of the font I choose the special characters are never showing up in the pdf.

**Comment by BCCHR-IT** [comment]
My mistake! Everything should be solved in the new release then.
