### ISSUE TITLE
ckeditor version 4.11.4 is insecure

### ISSUE THREAD

**Issue by DannyHGit** [BCCHR-IT/custom-template-engine#44]
Hello,
We have been using this module in REDCap and our most recent pentest indicated that ckeditor version 4.11.4 that is included in Custom Template Engine - v3.1.1  contains several cross-site scripting vulnerabilities.

Can we please create an updated version.

Thankyou

**Comment by BCCHR-IT** [comment]
Hello @DannyHGit ,

We are about to release CTE v3.2.0, which has an upgraded ckeditor to 4.21. I will close this issue.
