### ISSUE TITLE
Template engine is not populating records in the drop down

### ISSUE THREAD

**Issue by debbieb72** [BCCHR-IT/custom-template-engine#46]
A few weeks ago, the template engine stopped populating records from which to select in the dropdown, though is indicating the correct number of records available.  

This screenshot shows that 22 record are available (which is correct), however the dropdown is not populating with any records from which to select to populate the template.  The problem seems to be somewhere within in this code repository. Could you please advise? Thank you.
![image](https://user-images.githubusercontent.com/131173941/232800368-13ab6192-8f1c-4707-93e1-95d99f7e1b91.png)

**Comment by RobertAndersonHunt-PeterMac** [comment]
Hi team,

Same issue for us in our instance - 

![image](https://user-images.githubusercontent.com/62044593/234443584-3ddf5144-8dcb-4092-b380-96f868f68593.png)

The dropdown is not appearing on element click, but the li elements have been populated on page load:
![image](https://user-images.githubusercontent.com/62044593/234444097-a8c645f9-1107-45c5-9850-152bfaeb6c5e.png)

It looks like this might be linked to the recent change to Bootstrap 5; hovering over the relevant div element, the following error comes up:
![image](https://user-images.githubusercontent.com/62044593/234444393-38e00110-a144-4715-a641-8ba9e5293599.png)

Looks like the solve here would be to give the hidden list a title or name.

**Comment by BCCHR-IT** [comment]
Hello @debbieb72 and @RobertAndersonHunt-PeterMac ,

This is Dan Evans, the Dev team lead here at BCCHR. Thank you for the report.

I haven't been able to replicate this issue in our dev environment, likely because I'm using an old bootstrap. Do either of you have the capacity to test the suggested "name the list" fix?

**Comment by jasonrightmyer** [comment]
Dev Team,

It appears that the module is employing the "bootstrap-select" plugin (v1.13.15), which supports Bootstrap 4.0 only.  A Bootstrap 5.0 compatible version is in beta (v1.14.0-beta3).  A quick fix appears to fix the problem, but its not fully tested (see below).  A stable plugin release is eventually required.  

Replace lines 2565, 2566 in CustomTemplateEngine.php

- https://github.com/BCCHR-IT/custom-template-engine/blob/31bbd41cbc06fde7449f5080c164ad527f5a33a1/CustomTemplateEngine.php#L2565-L2566

with the following

`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/css/bootstrap-select.min.css">
		<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/js/bootstrap-select.min.js"></script>`

**Comment by BCCHR-IT** [comment]
@debbieb72 v3.2.1 -- soon to be released -- will include the changes to fix this bug. Thank you to @jasonrightmyer for the assist!

**Comment by BCCHR-IT** [comment]
v3.2.1 has been submitted for review, so will close this issue.
