### ISSUE TITLE
format dates and calculate BMI

### ISSUE THREAD

**Issue by jhscoordinatingcenter** [BCCHR-IT/custom-template-engine#5]
by default the date is showing as YYYY-MM-DD. can we change to MM/DD/YYYY. Also, I have Height and Weight. Can I calculate BMI on the report

**Comment by BCCHR-IT** [comment]
Hello,

Unfortunately, you cannot perform any calculations in the module, and this is not a feature we're looking to add soon. 

As for the date, its format will depend upon the date validation of its REDCap field, and adding formats beyond those is not something we plan on doing soon. You may change your date manually, before downloading, but I understand this may be time consuming.
