### ISSUE TITLE
REDCap version lock

### ISSUE THREAD

**Issue by Seaborg** [BCCHR-IT/custom-template-engine#53]
Hi, I can see that the new version is set to maximum REDCap version to 12.1.x.
Are there any plans to port it to 13.7.x ? We need to update REDCap version due to
security vulnerabilities in older versions. 
Which features are broken in later REDCap 13.7.x?

**Comment by BCCHR-IT** [comment]
Hi @Seaborg I am submitting CTE v4.0.0 which is compatible with RC v12.4+ and PHP 7.4+ hopefully today to the consortium for review.
