### ISSUE TITLE
Donwload PDF: make optional page number and timestamp to every page

### ISSUE THREAD

**Issue by itcerp** [BCCHR-IT/custom-template-engine#6]
Hi,
Thanks a lot, excellent module!
Could it be optional to add, or not, page number and timestamp to every page?
Enable/disable script from function downloadTemplate(), Lines 1213-1225 (v2.9.4)

**Comment by BCCHR-IT** [comment]
Hello,
Glad you're enjoying the module! Unfortunately, we don't generally implement requests from outside our institute, so I can bring this up for discussion, but cannot guarantee it will be implemented.
