### ISSUE TITLE
Export rights not applying after version 14.3.4

### ISSUE THREAD

**Issue by RobertAndersonHunt-PeterMac** [BCCHR-IT/custom-template-engine#62]
Our instance recently updated to REDCap v14.3.4 and fields in all templates are returning [NO RIGHTS] for System Admins as well as users with data export rights in all instruments.

Is this an issue with our instance or with the module?

**Comment by BCCHR-IT** [comment]
Hi @RobertAndersonHunt-PeterMac ,
REDCap changed the way data export rights were returned by REDCap::getUserRights() with the release of the v14 branch. I am about to release v4.1.0 to address this.
