### ISSUE TITLE
PHP Error: Class "Smarty" not found...

### ISSUE THREAD

**Issue by RobertAndersonHunt-PeterMac** [BCCHR-IT/custom-template-engine#65]
Hi team,

After updating to the latest Engine version, this error appears when members of our team attempt to fill templates:

![image](https://github.com/BCCHR-IT/custom-template-engine/assets/62044593/14644780-b5c0-4092-a944-f66e01a4956e)

**Comment by BCCHR-IT** [comment]
Hi @RobertAndersonHunt-PeterMac , are you on a pre-v14.0 version of REDCap? If so, this bug will be fixed by v4.1.3, which should be released shortly.

**Comment by BCCHR-IT** [comment]
v4.1.3 has been released, please try that.

**Comment by BCCHR-IT** [comment]
And now v4.1.4. Will close this thread as the issue should have been resolved by one of the two updates released.
