### ISSUE TITLE
Disable Save Filled Reports to File Repository does not work

### ISSUE THREAD

**Issue by itcerp** [BCCHR-IT/custom-template-engine#7]
Hi, I've disabled option '**Save Filled Reports to File Repository**', but the pdf files are saved

**Comment by BCCHR-IT** [comment]
Hello, 
I'll need more information, before I can help. Can you screenshot your project settings for the module and the File Repository, and confirm whether the following message appears after you fill a template?:

"This module can save reports to the File Repository,  upon download. This is currently disabled, but if you'd like to enable this contact your REDCap administrator."

Can you also give me the date and approximate time you disabled the functionality?

**Comment by itcerp** [comment]
Redcap 9.6.3
Custom Template Engine - v2.9.4
I've disabled the funcionality just this week.
![ConfigureModule_CTE](https://user-images.githubusercontent.com/62018737/76415079-d8b2d980-6398-11ea-9679-f06ec360c8cb.png)
![ConfigureModule_CTE2](https://user-images.githubusercontent.com/62018737/76415090-de102400-6398-11ea-9b4e-e8252e9eac01.png)
![DonwloadTemplate_Filled](https://user-images.githubusercontent.com/62018737/76415899-59bea080-639a-11ea-822a-7861ad28ed3c.png)

**Comment by BCCHR-IT** [comment]
Hello, 
I don't think you meant to close this issue, so I'm reopening it. Your settings are fine, but could you also post a screenshot of your File Repository? Or, alternatively, download another report, and confirm that the timestamp is from after you've disabled saving.
