### ISSUE TITLE
Descriptive Text fields

### ISSUE THREAD

**Issue by jhscoordinatingcenter** [BCCHR-IT/custom-template-engine#8]
I do not see the Descriptive Text fields in the Click to View Fields as an option. I would like to display text based on the values. e.g:

SBP <120 and DBP <80 -  Your blood pressure was normal. 

SBP 120 < 120-129 and DBP <80 - Your blood pressure was somewhat elevated,

**Comment by BCCHR-IT** [comment]
Hello,
The module uses REDCap::getData() to retrieve record data, and since it does not include descriptive fields, they are not listed among the fields you can query with the module. You'll have to type the descriptive value out yourself.

**Comment by jhscoordinatingcenter** [comment]
Can you give an example.
I put {$redcap['desc_sbpnormal']} in the report but the text does not show up.

**Comment by BCCHR-IT** [comment]
Hello,
I meant you'd have to type the value out by hand. For example, "Your blood pressure was normal." instead of {$redcap['desc_sbpnormal']}.

**Comment by jhscoordinatingcenter** [comment]
This value depends on the blood pressure. If it normal show once descriptive (Your blood pressure was normal )if abnormal show different text(Your blood pressure was abnormal. Please consult your health care provider.

**Comment by BCCHR-IT** [comment]
Hello,
You can still use if statements, but you need to hand type the descriptive text you want within your if statement rather than using REDCap field names. In case you need an example:

{if (blood pressure is normal)}
Your blood pressure was normal 
{else}
Your blood pressure was abnormal. Please consult your health care provider
{/if}

**Comment by jhscoordinatingcenter** [comment]
Can you give an example how to use on the Custom Template Engine?

If SBP <120 and DBP <80 then “Your blood pressure was normal.”

Else if SBP 130-139 or DBP 80-89 then “Your blood pressure was high”

**Comment by BCCHR-IT** [comment]
Hello,

Please see below:

{if SBP <120 and DBP <80}
Your blood pressure was normal
{elseif (SBP >= 130 and SBP <= 139) or (DBP >= 80 and DBP <= 89)}
Your blood pressure was abnormal. Please consult your health care provider
{/if}

Please replace the fields in your conditionals with your REDCap field names, like SBP = $redcap['sbp_var_name'].

**Comment by jhscoordinatingcenter** [comment]
ERROR MESSAGE: Please advise
 [EDITOR] LINE [23] Report logic cannot have any HTML between {}
{if {$redcap['sbp111']}<120 and {$redcap['sbp112']}<80}
Your blood pressure was normal.
{/if}

**Comment by BCCHR-IT** [comment]
Hello,
First, please remove the brackets around the redcap fields. You cannot have any nest curly brackets. An  example of the proper syntax should be under the Syntax rules. So your text would be:

{if $redcap['sbp111'] < 120 and $redcap['sbp112'] <80}
Your blood pressure was normal.
{/if}

As for your other issue, please navigate to the Source view, and go to the line indicated in the error. There should not be any HTML between any curly brackets. Please remove any if you see them.

**Comment by jhscoordinatingcenter** [comment]
<p>{if $redcap[&#39;sbp111&#39;] &lt; 120 and $redcap[&#39;sbp112&#39;] &lt;80}</p>

<p><span style="font-size:14px">Your blood pressure was normal.</span></p>

<p><span style="font-size:14px">{/if}</span></p>

**Comment by BCCHR-IT** [comment]
Hello,
Apologies, I forgot to say the operators must be replaced with their text equivalents. Please refer to the table under the Syntax rules for other logical operators, but use the example below. 

{if $redcap['sbp111'] lt 120 and $redcap['sbp112'] lt 80}
Your blood pressure was normal.
{/if}

**Comment by jhscoordinatingcenter** [comment]
Could you send me the link to the table for syntax rumes

**Comment by BCCHR-IT** [comment]
Hello,
They should be visible when you create/edit a template. Please see under 'Use a combination of comparison operators to build more complex syntax.' These are the operators the template engine uses.

**Comment by jhscoordinatingcenter** [comment]
The date format by default is YYYYMMDD from redcap, how to change to MM/DD/YYYY format on the report?
Individuals who have received this information in error or are not authorized to receive it must promptly return or dispose of the information and notify the sender. Those individuals are hereby notified that they are strictly prohibited from reviewing, forwarding, printing, copying, distributing or using this information in any way.

**Comment by BCCHR-IT** [comment]
There's no way to change the date format when filling a report. You'll have to change it by hand in the preview before downloading.
