### ISSUE TITLE
Crashes on Download/Enabling

### ISSUE THREAD

**Issue by jasonlones** [BCCHR-IT/custom-template-engine#9]
Upon downloading and enabling module from repo, module will not load correctly.  Soft crashes REDCap which sends repeated emails indicating the following:

> Could not instantiate the 'custom_template_engine' module because of the following error:
> 
> Error Message: Cannot declare class Smarty, because the name is already in use
> File: /var/www/html/redcap/modules/custom_template_engine_v2.9.4/vendor/smarty/smarty/libs/Smarty.class.php
> Line: 0

After several emails, a different email:

> Could not instantiate the 'custom_template_engine' module, but a specific cause could not be detected. This could be caused by a die() or exit() call in the module which needs to be replaced with an exception to provide more details, or a $module->exitAfterHook() call to allow other modules to execute for the current hook.

Finally:

>  The 'custom_template_engine' module was automatically disabled because of the following error:
> 
> Exception: The 'custom_template_engine' module MUST specify a 'namespace' in it's config.json file. in /var/www/html/redcap/redcap_v9.5.19/ExternalModules/classes/ExternalModules.php:2621
> Stack trace:
> #0 /var/www/html/redcap/redcap_v9.5.19/ExternalModules/classes/ExternalModules.php(1503): ExternalModules\ExternalModules::getModuleInstance('custom_template...', 'v2.9.4')
> #1 /var/www/html/redcap/redcap_v9.5.19/Classes/Jobs.php(98): ExternalModules\ExternalModules::validateAllModuleCronJobs()
> #2 /var/www/html/redcap/redcap_v9.5.19/Classes/Cron.php(311): Jobs->ExternalModuleValidation()
> #3 /var/www/html/redcap/redcap_v9.5.19/cron.php(22): Cron->execute()
> #4 /var/www/html/redcap/cron.php(11): include('/var/www/html/r...')
> #5 {main}

Module must be deleted from the server to stop cycle.

Thanks!

**Comment by BCCHR-IT** [comment]
Hello,

Apologies for the late response. Thanks for checking out the module!

For the first issue, it's indicating that a dependency (in this case, Smarty) required by the template engine is already in use somewhere else in REDCap. Are you using Smarty anywhere else, or have our old Custom Report Engine installed? If so, the template engine will not work.

Unfortunately, we've never experienced the last two issues, but please check the first issue, and let us know if it resolves your problems. I suspect that may be the cause.
